### ISSUE TITLE
Related resource get_links returns wrong related_link

### ISSUE THREAD

**Issue by noazark** [django-json-api/django-rest-framework-json-api#175] opened 2015-12-18 19:39 UTC
I believe I've run into a bug in the configuration of related resource links. I think the issue starts here:

[rest_framework_json_api/relations.py#L101](https://github.com/django-json-api/django-rest-framework-json-api/blob/79b7c79f0c19fdda77dfc62e2ad58cedaad73033/rest_framework_json_api/relations.py#L101)

The `related_kwargs` dict is not actually configurable. The `related_link_lookup_field` is only used to access `kwargs`, which, because `get_links` [is not called with any kwargs](https://github.com/django-json-api/django-rest-framework-json-api/blob/79b7c79f0c19fdda77dfc62e2ad58cedaad73033/rest_framework_json_api/renderers.py#L160), has a kwarg `lookup_field` and is defaulted to "pk". It is rarely, if ever, that the child's lookup field is the parent's primary key, therein lies the problem. Here is an example of the **incorrect** output:

``` json
{
  "data": {
    "id": 241,
    "relationships": {
      "previous-shipment": {
        "data": {
          "type": "shipment",
          "id": "1439417"
        },
        "links": {
          "self": "http://localhost:8000/api/account/241/relationships/previous_shipment",
          "related": "http://localhost:8000/api/shipment/241/"
        }
      }
    },
    "type": "account"
  }
}
```

You'll notice that the related link _should_ be http://localhost:8000/api/shipment/1439417

**Possible solution**

I'll happily make a PR for this, but it's confusing enough that I want to make sure I'm on the right track.

My guess is that the `related_kwargs` is just getting set wrong. The assignment seems to be a reflection of the assignment on [L95](https://github.com/django-json-api/django-rest-framework-json-api/blob/79b7c79f0c19fdda77dfc62e2ad58cedaad73033/rest_framework_json_api/relations.py#L95). If that is the case, I think the code is just a bit off (this was tested and works):

``` py
related_kwargs = {self.related_link_url_kwarg: getattr(obj, self.related_link_lookup_field) if obj else kwargs[self.related_link_lookup_field]}
```

**Comment by jerel** [comment] 2015-12-19 16:01
@noazark thanks for reporting this. I think you are correct in your assessment and I'd welcome a PR with an accompanying test. Tests for relationships [are here](https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/example/tests/test_relations.py). Feel free to add an integration test to that existing file or if you add a new unit test it should go in [example/tests/unit](https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/example/tests/unit). (we're slowly converting tests to pytest format in ./unit and ./integration)

@jsenecal or @leifurhauks since you wrote the relationships feature do you agree that this behavior is incorrect as described?

**Comment by Anton-Shutik** [comment] 2015-12-21 13:07
@noazark Great catch! Thank you!
My fix is here: https://github.com/django-json-api/django-rest-framework-json-api/pull/177/files

**Comment by jsenecal** [comment] 2015-12-21 15:01
@jerel @noazark, while your description of the bug seems to be correct, there might be something going on in your actual implementation as, for my use-case anyways the behavior is correct:

```json
{
	"data": {
		"type": "organization",
		"id": "1007",
		"attributes": {
			"permissions": {
				"delete": true,
				"view": true,
				"add": true,
				"change": true
			},
			"created_at": "2015-12-18T18:26:06.957225Z",
			"modified_at": "2015-12-18T18:26:06.962126Z",
			"removed": null,
			"name": "Test corp ldt.",
			"nickname": null,
			"reference": "tes001",
			"notes": null
		},
		"relationships": {
			"children": {
				"meta": {
					"count": 0
				},
				"data": [],
				"links": {
					"self": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/relationships/children",
					"related": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/children"
				}
			},
			"parent": {
				"data": null,
				"links": {
					"self": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/relationships/parent",
					"related": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/parent"
				}
			},
			"resellers": {
				"meta": {
					"count": 0
				},
				"data": [],
				"links": {
					"self": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/relationships/resellers",
					"related": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/resellers"
				}
			},
			"customers": {
				"meta": {
					"count": 0
				},
				"data": [],
				"links": {
					"self": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/relationships/customers",
					"related": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/customers"
				}
			},
			"departments": {
				"meta": {
					"count": 0
				},
				"data": [],
				"links": {
					"self": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/relationships/departments",
					"related": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/departments"
				}
			},
			"people": {
				"meta": {
					"count": 0
				},
				"data": [],
				"links": {
					"self": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/relationships/people",
					"related": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/people"
				}
			},
			"administrators": {
				"meta": {
					"count": 0
				},
				"data": [],
				"links": {
					"self": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/relationships/administrators",
					"related": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/administrators"
				}
			},
			"email_domains": {
				"meta": {
					"count": 0
				},
				"data": [],
				"links": {
					"self": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/relationships/email_domains",
					"related": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/emaildomains"
				}
			},
			"phone_numbers": {
				"meta": {
					"count": 0
				},
				"data": [],
				"links": {
					"self": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/relationships/phone_numbers",
					"related": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/phonenumbers"
				}
			},
			"email_addresses": {
				"meta": {
					"count": 0
				},
				"data": [],
				"links": {
					"self": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/relationships/email_addresses",
					"related": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/emailaddresses"
				}
			},
			"urls": {
				"meta": {
					"count": 0
				},
				"data": [],
				"links": {
					"self": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/relationships/urls",
					"related": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007/urls"
				}
			},
			"tags": {
				"meta": {
					"count": 0
				},
				"data": []
			}
		},
		"links": {
			"self": "https://api-dev.zerofail.com:8443/api/contacts/organizations/1007"
		}
	}
}
```

There is however potential improvement possible on to how to select from what field the URL should be constructed from.

**Comment by Anton-Shutik** [comment] 2015-12-21 16:52
@jsenecal Yep, that works fine for you since there is no OneToOne reations in your example.

**Comment by Anton-Shutik** [comment] 2016-04-15 07:32
I think @noazark was wrong saying that related link should look like:
 **http://localhost:8000/api/shipment/241/**.
I think it should look like:
**http://localhost:8000/api/account/241/shipment/**

Because it follows the spec, while first one does not:

> Additionally, a related resource link MUST NOT change because its relationship's content changes.

http://jsonapi.org/format/#document-resource-object-related-resource-links

So, the link should stay the same even if the shipment will be changed.

Any more opinions?

**Comment by luissalgadofreire** [comment] 2016-12-16 19:11
Hi. I'm trying out this library and just came to the same problem as pointed out by @noazark above.
To-one relationships don't work correctly as per below, where 331 is the `language_pk`, not `country`'s, and the link doesn't follow the json-api spec as pointed out by @Anton-Shutik:

`"relationships": {
   "country": {
     "links": {
       "self": "http://192.168.99.101/api/i18n/languages/331/relationships/country",
       "related": "http://192.168.99.101/api/i18n/countries/331/"`

Is there any follow-up on this or could you point out a workaround to deal with this? The example in docs only describes the to-many case; and I can't just get this to work with to-one relationships.

**Comment by Anton-Shutik** [comment] 2018-08-01 10:11
@sliverc I think this can be closed, since it is not a bug

**Comment by sliverc** [comment] 2018-08-02 06:58
I agree it seems this is an implementation issue and not an issue of DJA itself.

Let me close this but if there are still questions concerning this issue please comment and we can reopen.

**Closed by sliverc** 2018-08-02 06:58 UTC
