### ISSUE TITLE
Are the docs incorrect for including related data?

### ISSUE THREAD

**Issue by erichonkanen** [django-json-api/django-rest-framework-json-api#311] opened 2016-12-22 07:59 UTC
Hello,

Coming back to this package after using `ember-django-adapter` for awhile and while trying to figure out how to include side-loaded related data, I notice that the docs say it is handled automatically. However in practice out-of-the-box this package does not include the `included` key with the related data unless I explicitly declare `JSONAPIMeta` like so:
```
class UserSerializer(ModelSerializer):
    account = AccountSerializer(read_only=True)

    class JSONAPIMeta:
        included_resources = ['account']
```
Is this by design or is something not hooked up right? For nested/related serializers should the docs explain that you must include the `included_resources` property? I was only able to find this via stackoverflow and another issue on here.

[This](http://django-rest-framework-json-api.readthedocs.io/en/stable/api.html#extract-included) page is the only page in the docs that even references the property `included_resources` but does nothing to explain how to use it.

Thanks

**Comment by jerel** [comment] 2016-12-22 16:29
The original behavior was that `include` must be passed in the URL in order
to have included data returned. Then `included_resourced` was added later
as a way of including them by default. It's possible that the docs could be
expanded on that topic.

On Dec 22, 2016 2:00 AM, "Eric Honkanen" <notifications@github.com> wrote:

Hello,

Coming back to this package after using ember-django-adapter for awhile and
while trying to figure out how to include side-loaded related data, I
notice that the docs say it is handled automatically. However in practice
out-of-the-box this package does not include the included key with the
related data unless I explicitly declare JSONAPIMeta like so:

class UserSerializer(ModelSerializer):
    account = AccountSerializer(read_only=True)

    class JSONAPIMeta:
        included_resources = ['account']

Is this by design or is something not hooked up right? For nested/related
serializers should the docs explain that you must include the
included_resources property? I was only able to find this via stackoverflow
and another issue on here.

(this)[http://django-rest-framework-json-api.readthedocs.io/en/stable/api.
html#extract-included] page is the only page in the docs that even
references the property included_resources but does nothing to explain how
to use it.

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/django-json-api/django-rest-framework-json-api/issues/311>,
or mute the thread

**Comment by sliverc** [comment] 2018-05-03 14:03
This should have been addressed with #308 and http://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html?highlight=included_serializers#included

Closing issue. Please comment if something is still not clearly documented concerning this feature.

**Closed by sliverc** 2018-05-03 14:03 UTC

**Comment by nattyg93** [comment] 2019-02-18 02:03
Hi @sliverc,

I think the wording of this section is a bit ambiguous. These two sentences: "The two required additions are `included_resources` and `included_serializers`." and "`included_resources` informs DJA of what you would like to include." seem to imply that `included_resources` is required. And there is no indication that `included_resources` simply informs dja of which resources to include by _**default**_.

**Comment by sliverc** [comment] 2019-02-18 14:15
@nattyg93 
I agree this could be misleading. Would you mind opening a PR clarifying this difference?  That would be great.

**Comment by nattyg93** [comment] 2019-02-19 04:35
@sliverc
I'll take a look on the weekend if I've got the time. 👍
