### ISSUE TITLE
id field set on ModelSerializer is bypassed and not used

### ISSUE THREAD

**Issue by erichonkanen** [django-json-api/django-rest-framework-json-api#323] opened 2017-02-06 08:52 UTC
We noticed that the `id = serializers.SerializerMethodField()` that we have set on our `ModelSerializer` is not being used when this package creates the json-api structure. Upon investigating I saw this line which appears to use the `resource_object.pk` for the `id` field:

https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/renderers.py#L387

```
class FooSerializer(ModelSerializer):
    id = serializers.SerializerMethodField()

    def get_id(self, obj):
        """
        Returns the Foo.short_id as `id` for the client.
        """
        return shortuuid.serialize_uuid(obj.id).decode('utf-8')
```

This causes a bug where if someone has written a custom serialized `id` field it is bypassed completely. In our case we are customizing the id of our model for the client.

We may create a shortcut locally but I think this package should respect anything defined in the local serializers and use that rather than bypassing it. It also brings up a question on using this package in general: does this package change the way fields must be defined compared to the typical DRF way? Does it automatically translate the normal DRF serializer fields into the appropriate json-api versions? I realize it's somewhat complex so just trying to gauge how this will affect writing serializers for our project

**Comment by mwisner** [comment] 2017-03-01 13:42
I think this might be related to:
https://github.com/django-json-api/django-rest-framework-json-api/pull/165
https://github.com/django-json-api/django-rest-framework-json-api/issues/155

**Comment by sliverc** [comment] 2018-05-23 06:41
I am closing this as a duplicate of #155. If there are any more comments concerning this, please comment there.

**Closed by sliverc** 2018-05-23 06:41 UTC
