### ISSUE TITLE
Django 2.0

### ISSUE THREAD

**Issue by mapeveri** [django-json-api/django-rest-framework-json-api#397] opened 2018-01-06 23:29 UTC
Hi, in django 2.0 i have this error:

`ImportError: Could not import 'rest_framework_json_api.parsers.JSONParser' for API setting 'DEFAULT_PARSER_CLASSES'. ImportError: No module named 'django.core.urlresolvers'.`

With the version: djangorestframework-jsonapi==2.3.1

I see that the code already solves the problem of URL summaries. Can not release a version to work comfortably with the library?

Thanks!

**Comment by mblayman** [comment] 2018-01-07 00:19
Yes, the current version of DJA does not support Django 2.0 because it does not support DRF 3.7. The Pull Request (#394) that adds support is currently blocked while we wait for one of the dependencies to support Django 2.0.

Since this is a duplicate of #388, I'm going to close this one. Thanks!

**Closed by mblayman** 2018-01-07 00:19 UTC

**Comment by mapeveri** [comment] 2018-01-07 00:28
@mblayman That is, it depends on django-polymorphic?. Only then can the new version be released?.

Thanks!

**Comment by mblayman** [comment] 2018-01-07 00:46
You're correct. django-polymorphic is the dependency that needs to work for Django 2.0. A large part of the test suite is affected by that package.

I will put out a release quickly once there are no more blockers. Thanks for your patience.

**Comment by mapeveri** [comment] 2018-01-07 00:48
Ok thanks!. Anything that can help with pleasure :)
