### ISSUE TITLE
sideloaded models (compound documents)

### ISSUE THREAD

**Issue by andorov** [django-json-api/django-rest-framework-json-api#113] opened 2015-10-01 15:41 UTC
class PostSerializer(serializers.ModelSerializer):
        class Meta:
            model = Post
            fields = ('name', 'comments')

        comments = CommetSerializer(many=True,read_only=True)

This works properly for `http://127.0.0.1:8000/posts/1` (ie has the appropriate comments in `included` at the top level).

However `http://127.0.0.1:8000/posts` returns the error `'NoneType' object has no attribute 'comments'`.

**Comment by jsenecal** [comment] 2015-10-01 16:27
Please write a failing test for this so we can replicate you use case.

**Comment by wismer** [comment] 2015-10-01 20:13
@jsenecal I've spent a little time trying to replicate (as I'm experiencing a similar issue) but haven't come up with anything concise. When `WorkOrderViewSet` is set as a `ModelViewSet`, I get that error that @andorov mentions. But when I switch it out for `ReadOnlyViewSet`, it works fine. Apparently `create()` is being called but I can't tell why that is.

```python
# view
class WorkOrderViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = WorkOrder.objects.all()
    serializer_class = WorkOrderSerializer
    resource_name = 'work_orders'
```

```python
# serializers
class PartSerializer(serializers.ModelSerializer):
    class Meta:
        model = Part
        exclude = ('work_order',)


class LaborSerializer(serializers.ModelSerializer):
    class Meta:
        model = Labor
        exclude = ('work_order',)


class WorkOrderSerializer(serializers.ModelSerializer):
    included_serializers = {
        'part_set': PartSerializer,
        'labor_set': LaborSerializer
    }

    part_set = PartSerializer(many=True, read_only=True, required=False)
    labor_set = LaborSerializer(many=True, read_only=True, required=False)

    class Meta:
        model = WorkOrder
        exclude = ('parent_order',)
```

**Comment by jsenecal** [comment] 2015-10-05 20:27
We recently merged some work I've been doing on supporting compound documents - https://github.com/django-json-api/django-rest-framework-json-api/commit/cf8a930268c152d14b9ac9f4c337fdbf61ee1e0e#diff-a16d805758b2ef29db6bd4ff77e9ccfbR418 - for this to work, you need to define an `included_serializers` dict along with the fields of your serializers, like so:
```python
    included_serializers = {
        'customers': 'self',
        'resellers': 'self',
        'people': PersonSerializer
    }
```
Let me know if you face the same issues.

**Comment by jsenecal** [comment] 2015-10-09 14:36
@andorov; @wismer Since I haven't heard from you I will now close this issue. Feel free to reopen if the issue is still present when pulling the latest code from the develop branch.

**Closed by jsenecal** 2015-10-09 14:36 UTC
