### ISSUE TITLE
Error using a filter with a suffix

### ISSUE THREAD

**Issue by eloi-martinez-qida** [django-json-api/django-rest-framework-json-api#1088] opened 2022-09-12 16:30 UTC
## Description of the Bug Report
I have a django FilterSet in a view that filters a date with DateFromToRangeFilter.
date_before=yyyy-mm-dd works fine but
filter[date_before]=yyyy-mm-dd
rises a:
ValidationError
rest_framework.exceptions.ValidationError: [ErrorDetail(string='invalid filter[date_before]', code='invalid')]

## Checklist

- [x] Certain that this is a bug (if unsure or you have a question use [discussions](https://github.com/django-json-api/django-rest-framework-json-api/discussions) instead)
- [x] Code snippet or unit test added to reproduce bug

class XXXXFilter(FilterSet):
    date = DateFromToRangeFilter(field_name='date')

    class Meta:
        model = XXXXX
        fields = ()

**Comment by sliverc** [comment] 2022-09-12 18:44
Thanks for reporting. This is I feel a duplicate of #938 Closing this issue, therefore. If there are additional comments to this issue, feel free to add comments to the respective issue.

**Closed by sliverc** 2022-09-12 18:44 UTC
Labels: bug
