### ISSUE TITLE
Query explosion even on simple models with no included serializers

### ISSUE THREAD

**Issue by aidanlister** [django-json-api/django-rest-framework-json-api#337] opened 2017-04-14 12:14 UTC
I love the idea of this module but it seems like it's impossible to build fast APIs with it.

Let's say I have Books and Authors. I fetch a list of books, even with no "included" specified I get a query for each author, just to display the FK?

As a broader issue, as Author increases in complexity developers will add more included_serializers to that serialiser, which inadvertently affects my Books viewset with a query explosion.

Could we define a lambda for each included_serializer to alter the query? Anything more robust than magic.

**Comment by mblayman** [comment] 2017-04-14 13:29
@aidanlister thanks for your concern about performance. As a production user of DJA, I want my site to be performant too. The built-in DJA `ModelViewSet` uses a `prefetch_related` on querysets to avoid an N+1 query bug when including additional models. Do you have a specific example and/or data to explain the "query explosion" that you're referring to?

FYI, there was a recent bug that was fixed (which I don't think has been released yet) that was preventing the `prefetch_related` code from executing. Ideally, a DJA model viewset should only have to do 1 db query for each included model type. If that's not the behavior you're seeing in practice, then maybe there is another bug.

**Comment by aidanlister** [comment] 2017-04-14 23:52
@mblayman so load up the example app, generate some fake data:

```
factories.CommentFactory.bulk_create(50)
```

Then look at the comments list:

<img width="1291" alt="screen shot 2017-04-15 at 9 51 34 am" src="https://cloud.githubusercontent.com/assets/54896/25058836/301480ec-21c1-11e7-86a2-089a43227170.png">


We can see there's 5 comments, but 15 queries, and no included relationships ... it's doing a query just to display the FK.

**Comment by aidanlister** [comment] 2017-04-15 00:58
I've added a failing test,
https://github.com/ABASystems/django-rest-framework-json-api/commit/0df9244efeed0b47a0163b41dddab77d5f93ee13

**Comment by mblayman** [comment] 2017-04-15 02:38
Thanks @aidanlister, that's really helpful info. I agree that seems wrong for sure.

It seems like the next steps are to track down those excessive queries and find a way to delay evaluation or group things together to reduce the number to where it should be.

**Comment by aidanlister** [comment] 2017-04-15 02:43
@mblayman I don't think it's about delaying the evaluation, we don't need a query to just show the FK.

I'll add a series of performance test cases to properly test this, but have you thought about providing a way of specifying the select related / prefetch related via a lambda or method on the serializer? Forcing it to be explicit seems better than magic.

**Comment by mblayman** [comment] 2017-04-15 02:48
Truthfully, I haven't given it a lot of thought. I stepped into a maintainer mode less than a couple of months ago. I'm not an expert in all the internal workings of the project, though I would like to understand it better.

Explicit over implicit definitely fits the Python ethos. I suspect that a reasonable default would be need to maintain backwards compatibility. Adding a method to help control the select_related / prefetch_related aspects of the serializer sounds good.

I'm trying to fire up the example now so I can look at the queries and see where the library is being wasteful.

**Comment by mblayman** [comment] 2017-04-15 03:50
Ok, I got the example app going and debug toolbar is showing me that each comment in the comment listing is adding two queries. This is definitely an N+1 bug because debug toolbar shows the extra queries come from fetching the author and entry from each comment to get the respective IDs. I think the problem is in the example app's viewset code.

With 4 comments, I had 12 queries. Some are unavoidable because of the need to get the count and use the paginator (as you noted in your test). 8 queries came from each of the 4 comments fetching author and entry.

I went to the `CommentViewSet` and changed the queryset:
```python
    queryset = Comment.objects.all().select_related('author', 'entry')
```

After this change, the query count dropped to 5 and stayed there even when I added more comments.

I *do* see the possibility to optimize the model serializer to use `entry_id` instead of `entry.id` (for example). That would be a nice benefit to avoid going to the entry db table entirely since the ID is stored in the foreign key field of the comment model. I think this pattern could generalize.

**Comment by aidanlister** [comment] 2017-04-15 03:59
Ahhhh, yes you're right, it's the author.id that's causing it to blow out. If we can fix that, that solves a good chunk of my issue.

**Comment by aidanlister** [comment] 2017-04-15 04:14
Looks like line 120 in renderers.py,
resolved, relation_instance = utils.get_relation_instance(resource_instance, source, field.parent)

?

**Comment by aidanlister** [comment] 2017-04-15 04:53
Actually I take that back ... the renderer has no effect.

Line 143, Json API ModelSerializer has this:
``` serializer_related_field = ResourceRelatedField ```

Somewhere in ResourceRelatedField ...

**Comment by aidanlister** [comment] 2017-04-15 06:27
So, on ResourceRelatedField, we set use_pk_only_optimization = False,

```
class ResourceRelatedField():
    def use_pk_only_optimization(self):
        # We need the real object to determine its type...
        return False
```

This means that this method from the parent class (PrimaryKeyRelatedField) runs:

```
    def get_attribute(self, instance):
        if self.use_pk_only_optimization() and self.source_attrs:
            # Optimized case, return a mock object only containing the pk attribute.
            try:
                instance = get_attribute(instance, self.source_attrs[:-1])
                value = instance.serializable_value(self.source_attrs[-1])
                if is_simple_callable(value):
                    # Handle edge case where the relationship `source` argument
                    # points to a `get_relationship()` method on the model
                    value = value().pk
                return PKOnlyObject(pk=value)
            except AttributeError:
                pass

        # Standard case, return the object instance.
        return get_attribute(instance, self.source_attrs)
```

The optimized case is what stops the query explosion ordinarily, it creates a mock object (PKOnlyObject) with only the PK set so that there's no object lookup.

@jsenecal looks like you made the commit two years ago, any insight?

https://github.com/django-json-api/django-rest-framework-json-api/commit/23d0af686ca9ad69ac8c63f45a7a08bf9656a459

**Comment by aidanlister** [comment] 2017-04-15 10:01
I think I'm getting there ... this has resolved the number of queries, but I had to kill some functionality.

https://github.com/ABASystems/django-rest-framework-json-api/commit/94f79c4c6370fd2bc0bb35440163e20b193bfa14

**Comment by aidanlister** [comment] 2017-04-15 11:28
I think I've gone as far as I can go with this ... 

This is a simple pattern I've used for managing the queryset based on what is included, I think this makes sense:
```
class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

    def get_queryset(self):
        qs = super().get_queryset()
        if 'author' in self.request.GET.get('include', '').split(','):
            qs = qs.prefetch_related('author')
        return qs
```

The other location I mentioned before was also causing an explosion, the simplest fix is removing the get links functionality:

```
field_links = field.get_links(resource_instance)
```

**Comment by aidanlister** [comment] 2017-04-15 13:05
This is where I've finished up:

https://github.com/django-json-api/django-rest-framework-json-api/compare/develop...ABASystems:hotfix/performance?expand=1

**Comment by aidanlister** [comment] 2017-04-22 06:05
@mblayman have you had a chance to take a look at this yet?

**Comment by mblayman** [comment] 2017-04-22 12:47
No, I stopped looking at it. I thought the conversation reached a conclusion for your case, and you were reaching out to the other devs. I don't see anything directly actionable with this issue. The theme of this issue seems to be "find a way to use fewer queries." While I totally agree with the goal, without a PR and some code that attempts to reduce the query count, I don't see what we could do next with this issue.

**Comment by aidanlister** [comment] 2017-04-23 08:11
@mblayman ah, I assumed when you said you were the maintainer that you meant the package was actively maintained.

The package has an m*(n+1) bug where m is the number of relations a model has, n is the page size, making it completely unsuitable for any production environment or large data sets.

So I guess I'm worried if the package isn't being actively maintained we might need to rethink our API strategy.

**Comment by mblayman** [comment] 2017-04-23 13:16
As a community effort, this project depends on contributions from the community. It *is* actively maintained and had a release on Friday for 2.2 which includes many months of contributions from a wide variety of individuals.

I respectfully disagree with your conclusion that it is "**completely** unsuitable for **any** production environment or large data sets" (emphasis added). Aside from being hyperbolic (which I don't think is fruitful for technical conversation), I see this claim as false, knowing that I and many others have deployed DJA in a production setting.

IMO, the problem you are reporting is a limitation that is not unique to DJA. Selecting an appropriate queryset is true for DJA and DRF and Django underneath it. I think this is an area where Django (and Python in general) prefers being explicit over implicit. Rather than trying to intuit the appropriate `selected_related` additions, it is up to the developer to include this in the queryset. This strategy prevents code from over-selecting from other tables and bloating a db query. I thought I demonstrated that as I walked through how to eliminate the N+1 query bug from the example app. If I failed to make that clear enough, I apologize.

I think your comment from a few days ago (https://github.com/django-json-api/django-rest-framework-json-api/issues/337#issuecomment-294275533) gets at the heart of the piece that *can* be solved by a PR. If someone could find a way to make sure the ID is fetched from `model_id` instead of `model.id`, that would be awesome. I'd be happy to review a PR fixing this issue, however, I don't have the time to fix this myself.

**Comment by jsenecal** [comment] 2017-04-23 20:37
A long time ago, I needed this project to perform the required tasks needed
to be able to use this package for a production environment. As the project
was not mature enough to perform that task I decided I should contribute to
it and have the whole world benefit from it.

This is what I think Opensource should be, and not having people expect
everyone to do the hard work for them and complain about x or y feature
that could be missing even without knowing​ the actual work involved into
implementing those features.

This project was created to provide a Jsonapi compatible output for DRF, I
think it does that very well. I had to let go of the project because our
production project took a turn where we couldn't use Django resf framework
anymore, but hey, it was open source, so people took it from there and it
continued to evolve.

This is what's great about Opensource projects communities. - what's not so
great is actually having people complain without any form of respect for
the work that was accomplished.

... My two cents.

**Comment by jsenecal** [comment] 2017-04-23 20:44
To actually answer your original question:
Retrieving only the primary key of related objects was preventing any kind
of querying about those related objects the way that is required by the
JsonAPI format.

Unless this was fixed by change in the drf API, I don't think there is any
other solution to achieve the same results but we are open to suggestions.

**Comment by aidanlister** [comment] 2017-04-26 10:14
@jsenecal I'm not sure who's complaining about the package? Several of our developers have made contributions to this package over the last six months, I'm very glad it's available. In fact, our product depends on it. 

That's why I'm pretty worried that a critical issue like this was commented on with "I don't see anything directly actionable with this issue." ... perhaps my comment was a bit hyperbolic, but if I re-state it as "completely unsuitable for any production environment **with** large data sets" you might understand where I'm coming from.

Here's a scenario:

If you have a single model, e.g. Book, which has four relations e.g. Author, Publisher, CopyrightHolder, Category.

To display 25 books in DRF without any includes, I would need a single query: SELECT * FROM book.

To display 25 books DRF-JSONAPI without any includes, I would need either:
a) 1 query ala SELECT * FROM books LEFT JOIN author LEFT JOIN publisher LEFT JOIN CopyrightHolder LEFT JOIN Category
b) 4 queries with prefetches.

Let's say I have 1M books, 50k authors, 10k categories, 10k copyrightholders. In the select_related scenario, you've just created a in-memory table with 1e18 rows ... to display 25 rows, with no included relationships. So select_related is only going to work if you have a small dataset or a small volume of traffic.

So maybe we can do the prefetch option. Sure now we need 4x more queries, but at least they don't cause the database to melt down.

However, this doesn't scale with the app complexity. If you want to include the Author, Category and CopyrightHolder with the books, then you have to prefetch any relationships those models might have just to include them! You start ending up writing your ViewSet's like this:

```
class BookViewSet(ModelViewSet):
    queryset = Book.objects.all().prefetch_related(
        'book__author__tags',
        'book__author__client__tags',
        'book__author__client__primary_contact',
        'book__author__client__billingcard',
        'book__author__client__account',
        'book__copyrightholder__client__account_manager',
        'book__copyrightholder__client__clientgroup__accounts',
        'book__copyrightholder__branch__groups',
        'book__copyrightholder__branch__user_set',
        'book__publisher__address',
        'book__publisher__servicecontract_set',
        'book__publisher__account_manager',
        'book__property__billingcard',
        'book__service_group',
        'book__type__standard',
        'book__category_set__type',
        'book__type__categorytype_set',
    )
```

This is not a contrived example. That's an actual ModelViewSet we have though I had to slightly obfuscate the model names.

Once you have even a moderately complex app, it becomes impossible to stop query explosions as new relationships get added -- every model that might include that model's API needs to be updated.

So while I agree with you that my earlier comment was to some extent hyperbole, it depends on your definition of production, and if this isn't fixable then we're in deep shit and need to rethink our API strategy (which is of course, not your problem).

**Comment by aidanlister** [comment] 2017-04-26 10:33
@mblayman you talk about trying to serialize entry_id not entry.id but you need to understand how the serializer works, take a look at how DRF itself solves this issue see use_pk_only_optimization and PKOnlyObject.

@jsenecal have you got any time to help our team fix this? I've gone as far as I can. Surely somehow we can get the type from the relationship itself (not the model) and pass that to be used by the down stream serializer? I tried here... https://github.com/ABASystems/django-rest-framework-json-api/commit/94f79c4c6370fd2bc0bb35440163e20b193bfa14

Then maybe we can avoid doing work on models that aren't included, e.g. get_links shouldn't be called all the way down the stack ... https://github.com/ABASystems/django-rest-framework-json-api/commit/94f79c4c6370fd2bc0bb35440163e20b193bfa14#diff-e2e58e3e5c345fc3b14c160b3a00a64cL119

If that can't be done easily, would it be reasonable to create a fork of this package as a "fast mode" which aims to implement less of the spec, but does it in a reasonably performant way?

**Comment by mblayman** [comment] 2017-04-26 13:42
First, please allow me to apologize. Sometimes text really sucks as a communication format. 😄 While I wrote "I don't see anything directly actionable with this issue," it would have been more accurate to write "I see a few performance problems here and I don't know which of them we can/should focus on specifically."

Second, what is the outcome that your hoping for? It's pretty clear you're looking for a fix to these performance problems. You have provided a heroic amount of data and I appreciate that. I think the remaining problem is that you're hoping one of the maintainers will fix the performance issues. That's where I think this issue is crashing into the waves of open source. A quick peek at the contributor graph will reveal that the biggest contributors have not made code contributions in over 6 months (jerel's most recent stuff was doing the release work for 2.2). I was trying to be truthful calling the project "active." It is active in the sense that PRs get reviewed and merged and issues get commented on. It is not active in the sense that some person(s) is working on the reported issues with any regularity.

I think that leads us back to a pull request. From what you've written, it seems like your team is acutely feeling the pain of performance issues in your business. You've demonstrated really great knowledge of what the problem is and where it occurs. I will *happily* review any PRs that start to fix these performance issues. That's as much time as I can personally offer as this is a side project for me and no one is paying me to do any of this. 😄 

Thanks for your efforts so far.

**Comment by jsenecal** [comment] 2017-04-26 22:21
I'm all with @mblayman side on this as I unfortunately cannot currently
commit on any availability in the near future.

Hopefully this community wil be able to make good use of the submitted code
and solve your issues in a timely manner.

**Comment by aidanlister** [comment] 2017-05-02 21:39
@mblayman my goals were:

a) have a maintainer see the issue and fix it
b) if there's no maintainer time then get a point in the right direction
c) failing that, ensure that if we do commit the time and money to fixing the issue that it's a sensible investment, e.g. that the package is maintained and the maintainers are reasonable.

We've decided to go ahead and put some more senior developer time to fixing the issue, but I would like to have one of our team be added as a maintainer at some point, either @bor3ham, @jarekwg, or @sksavant once you're comfortable with their contributions and maintainer style.

@sksavant will follow up on this issue if he's able to come up with a solution.

**Comment by mblayman** [comment] 2017-05-02 21:58
Awesome! I'm excited to have other folks involved and look forward to any future contributions.

**Comment by emojiface-ops** [comment] 2017-06-14 03:03
@aidanlister appreciate your work on this issue, curious if you've gotten traction fixing the performance problems.

**Comment by aidanlister** [comment] 2017-06-14 10:28
Yes, actually the work I've done in this thread covers most of the issue, we expect to have a new production version up in the next four weeks.

**Comment by emojiface-ops** [comment] 2017-06-14 17:40
@aidanlister thanks for the quick response, I'll check out your fork. Are you planning to commit the "production version" on your fork?

**Comment by aidanlister** [comment] 2017-06-15 09:13
Yes, it should go through to our fork when it's finished ... and I'll submit a PR when we finish testing.

**Comment by emojiface-ops** [comment] 2017-06-15 16:41
Thanks! Much appreciated.

**Comment by xgilest** [comment] 2017-07-17 14:55
Hi, we've just found out today that we share this problem, a single 10 itmes list request hits 74 times de database, with only one include.
As we have our API in production, we are willing to contribute in the solution, as beta testers, reviewers or even coders if necessary and in our capacity.
Thank you

**Comment by jsenecal** [comment] 2017-07-17 16:08
If one of you guys can provide a demo app that showcases the problem, I can
try to fix this for you next week.

Let me know,

**Comment by emojiface-ops** [comment] 2017-07-18 02:47
Thanks @jsenecal ! 

@aidanlister @xgilest do you guys have a demo? If not I'll create one this week.

**Comment by emojiface-ops** [comment] 2017-07-18 19:15
Attached is a simple Django project that demonstrates a query explosion. Unzip and run the server:
```python manage.py runserver 127.0.0.1:8000```

Then hit this URL:
```http://127.0.0.1:8000/emojicollectionadded/?include=emoji_collection```

According to Django debug_toolbar, this causes 23 queries.

The API function is below. Because of the prefetch, I would expect far fewer queries:
```
class EmojiCollectionAddedViewSet(viewsets.ModelViewSet):
    queryset = EmojiCollectionAdded.objects.all()
    serializer_class = EmojiCollectionAddedSerializer

    def list(self, request):
        self.queryset = self.queryset.prefetch_related(
            'emoji_collection')
        return super(EmojiCollectionAddedViewSet, self).list(request)
```
[perftest.zip](https://github.com/django-json-api/django-rest-framework-json-api/files/1157019/perftest.zip)

**Comment by jsenecal** [comment] 2017-07-18 21:34
Thanks, I'll check it out tonight or tomorrow and see what I can do.

**Comment by jsenecal** [comment] 2017-07-19 17:30
FYI, for those willing to try the above code:
`requirements.txt` is missing few important modules:
```
django-autofixture
django-debug-toolbar
```

and `emoji/views.py` line no 2 had to be modified so that the `EmojiCollection` models are imported properly (might be a Py3 only issue though):
`from .models import EmojiCollection`

Now working on issue...

**Comment by emojiface-ops** [comment] 2017-07-19 17:45
Ah, forgot to freeze my requirements, thanks!

**Comment by jsenecal** [comment] 2017-07-19 18:18
Okay guys, it's been a long time since I worked on this code so help me out a bit ;)

I think we have to split this issue into several more:
1. Since we don't have the ability to predict what is expected from the api, we need a way to intercept the query and do the _prefetching_ ourselves dynamically such as to not pull the entire database every time someones checks an object as mentionned earlier by @aidanlister [here](https://github.com/django-json-api/django-rest-framework-json-api/issues/337#issuecomment-297335342)
2. Rewrite the module to allow for statically defined `types` so that one could avoid having to query everything in the models only to get pks from relations
3. ?


@aidanlister @emojiface-ops @mblayman @xgilest any ideas/comments on this ?

I made this a personal vendetta ahaha so help me out :)

**Comment by emojiface-ops** [comment] 2017-07-19 18:32
I vote for fixing #1. I'd wish I could contribute on how this would work, but I'm pretty new to python/django. Is this something you are able to tackle @jsenecal ? I can do grunt work in support.

**Comment by mblayman** [comment] 2017-07-19 18:46
I'm commenting without looking at the code or perf test project so please take my comment with a grain of salt. 😄 

Does the query size grow in scope because the code is doing things to fetch IDs (pks) from related models? To my knowledge, Django stores foreign keys in a model table with a convention of `foo_id`. If the query grows because it is looking up IDs in other tables, maybe we could get away with special casing the logic so that attributes look for `foo_id` instead of `foo.id`. I think there is already a bit of this kind of logic somewhere in the project.

I guess what I'm getting at is that I'm most interested in getting to the root of what causes the query to grow so large and I suspect that it's mostly related to ID lookup.

**Comment by emojiface-ops** [comment] 2017-07-19 18:52
@mblayman If I understand what you're getting at, my sample project was a little different. I was looking to get full included objects, not ID's. I prefetched the joined table inside the ViewSet so as to avoid N queries (1 query for each object), but the API still executed N queries. Does that make sense?

**Comment by jsenecal** [comment] 2017-07-19 19:44
Actually @emojiface-ops in the first zip provided you did not prefetch anything so the query explosion comes from what I mentioned in (1) above.
I will continue to work on this using the example app and a test done by @aidanlister

**Comment by emojiface-ops** [comment] 2017-07-19 19:54
@jsenecal OK maybe I'm misunderstanding. I thought the code below would prefetch EmojiCollection objects, which are joined via foreign key to EmojiCollectionAdded. If I'm doing this wrong, is there another way to prefetch in order to make sure there aren't N queries executed to retrieve each EmojiCollection?

```
    def list(self, request):
        self.queryset = self.queryset.prefetch_related(
            'emoji_collection')
        return super(EmojiCollectionAddedViewSet, self).list(request)
```

**Comment by aidanlister** [comment] 2017-07-19 23:18
Great that people are looking at this! @sksavant have you got anything to push or happy to hand it over?

@mblayman you keep saying use foo_id instead of foo.id but you need to actually look at the code, you are barking up the wrong tree.

@jsenecal there’s a performance test on my branch that you can run to demonstrate the issue, https://github.com/django-json-api/django-rest-framework-json-api/compare/develop...ABASystems:hotfix/performance?expand=1

The fixes required are:
1) fix the “pk only optimisation” to also pass the model (done, see my branch)
2) get rid of build_links on objects that havent already been fetched (commented out in my branch)

Everything else should be done by the user, e.g. prefetching or select related, but we might choose to add a helper to make this easier – I’ll paste the code we are using.

**Comment by jsenecal** [comment] 2017-07-19 23:21
Thanks for this, I think we kinda _have_ to make this prefetch automated or
at least configurable because most users will struggle with this without
actually seeing that there is a problem with their querysets.

I'll be giving this more time tomorrow, thanks!

**Comment by aidanlister** [comment] 2017-07-19 23:26
Here's our V2Mixin (e.g. for endpoints that use JSONAPI):

```
class V2Mixin:
    pagination_class = V2Pagination
    parser_classes = (
        rest_framework_json_api.parsers.JSONParser,
        rest_framework.parsers.FormParser,
        rest_framework.parsers.MultiPartParser,
        BulkActionJSONParser,
    )
    renderer_classes = (
        rest_framework_json_api.renderers.JSONRenderer,
        rest_framework.renderers.BrowsableAPIRenderer,
        JSONApiCSVRenderer,
        JSONApiGeoJSONRenderer,
        JSONApiAggregateRenderer,
    )
    metadata_class = rest_framework_json_api.metadata.JSONAPIMetadata

    def get_queryset(self):
        """ This lets us specify prefetch_for_includes on the viewset.

        This allows us to prefetch based on the includes specified in the URL:
        prefetch_for_includes = {
            'item': ['item__property', 'item__tags']
        }
        """
        qs = super().get_queryset()
        if not hasattr(self, 'prefetch_for_includes'):
            return qs

        includes = self.request.GET.get('include', '').split(',')
        for inc in includes + ['__all__']:
            prefetches = self.prefetch_for_includes.get(inc)
            if prefetches:
                qs = qs.prefetch_related(*prefetches)

        return qs

```

And this is the ViewSet:

```
class BookViewSet(V2Mixin, V2BulkUpdateViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    filter_class = BookFilterSet

    prefetch_for_includes = {
        '__all__': [
            'property',
            'task',
            'item',
            'technician',
            'product',
            'routine',
            'service',
        ],
        'item': [
            'item__tags',
            'item__remark_set',
            'item__type',
            'item__variant',
            'item__contractor',
            'item__property',
            'item__serviced_by',
        ],
        'item.remark_set': [
            'item__remark_set__failure',
        ],
    }
```

I'd advocate for something like this that we put into the documentation, rather than trying to magically guess (django favours explicit over implicit after all).

**Comment by emojiface-ops** [comment] 2017-07-19 23:31
Thanks @aidanlister; +1 for the 'explicit' approach

**Comment by mblayman** [comment] 2017-07-20 03:25
@emojiface-ops I had a chance to look at the perf test project this evening and have a couple of observations:

1. The code was using `ModelViewSet` from `rest_framework`. If you use the `ModelViewSet` from `rest_framework_json_api.views`, then you don't have to do the prefetch directly.
2. From what I saw in the debug toolbar, the code you provided *did* do the prefetch. The result of the prefetch is the third query on the `emoji_collection` table that has a WHERE clause full of IDs. Proof of the prefetch is visible if the line is commented out. Uncommented: 23 queries. Commented out: 42 queries.
3. Adding more to the `prefetch_related` can drop the query count from 23 to 4. I changed the code to the following:

```python
        self.queryset = self.queryset.prefetch_related(
            'emoji_collection', 'emoji_collection__emojis')
```

@aidanlister noted the verbosity of this restriction (i.e. needing to add more included stuff to the prefetch even for the nested stuff) in previously at https://github.com/django-json-api/django-rest-framework-json-api/issues/337#issuecomment-297335342.

As I consider the options for dealing with prefetch, I think I'm leaning toward @aidanlister's suggestion of being explicit. Having code that magically determines what to prefetch does sound nice in theory, however, I agree that Django favors explicit settings, and I think that code to automatically build the prefetch set might have some weird consequences.

One thing I don't understand is the gains from having an extra `prefetch_for_includes`. Are there some benefits from those class settings that I'm not seeing vs. using `prefetch_related` directly on the queryset?

**Comment by jsenecal** [comment] 2017-07-20 04:19
Thanks @mblayman for those observations I must have overlooked what was actually happening in the perftest project somehow and I must +1 everything else :) explicit with reasonable defaults could/should be the way to go.

I'm not sure I'm following what you mean by "prefetch_for_includes" in your conclusion question though...

I will work on porting the code @aidanlister has on his branch to our codebase and see how it helps then add the additional functionality to provide dynamic prefetching if possible.

I'll keep you guys updated on the progress...

**Comment by emojiface-ops** [comment] 2017-07-20 04:27
@mblayman You're totally right -- so the source of all the queries was pulling the second foreign key (Emoji table joined to EmojiCollection). Instead of just grabbing the id, it joined to the table. So the fix *is* just about making sure only the foreign key ID is returned (i.e. emoji_id).

**Comment by emojiface-ops** [comment] 2017-07-20 04:45
And, thinking more about it, to display the JSON snippet below, JSON_API needed to load an id from the "Emoji" table, which does require a separate query. So all those queries *are* necessary. At least for my specific case, (and @aidanlister may have different use cases), documenting this issue may be enough. In other words, I missed the fact I needed to prefetch "emoji" in this instance, since it wasn't included in the query string "include", yet it *was* included in the serializer.

    "included": [
        {
            "type": "emojicollections",
            "id": "0747945d-b395-4c8d-913e-aefab6aea00a",
            "attributes": {
                "name": "Ut qui aliquid iste a",
                "order": 0
            },
            "relationships": {
                "emojis": {
                    "meta": {
                        "count": 1
                    },
                    "data": [
                        {
                            "type": "emojis",
                            "id": "45a13e54-316b-4ed5-8653-9be09ba69da7"
                        }
                    ]
                }
            }
        },

**Comment by xgilest** [comment] 2017-07-20 09:45
Maybe my english limitations are responsible for my misunderstaning, but the problem has nothing todo with prefeching, the problem is the serializer making a query for every fk id on an object. So certanly prefetching can mitigate the problem, but it's not a solution in many cases.
Sure that prefeching for related is a very good feature too.
Has anyone looked at this?  @aidanlister  @sksavant

**Comment by aidanlister** [comment] 2017-07-20 10:49
@xgilest looked at what?

@mblayman want me to split up my work into PRs?

**Comment by aidanlister** [comment] 2017-07-20 12:48
Alright I've made three PRs.

These two should be fine to merge in, the first is just getting the stage set but no real changes.
- https://github.com/django-json-api/django-rest-framework-json-api/pull/364
- https://github.com/django-json-api/django-rest-framework-json-api/pull/365

The third is a partial solution which cuts the query count down ... but causes other issues with polymorphic models.
- https://github.com/django-json-api/django-rest-framework-json-api/compare/develop...ABASystems:feature/fix-query-explosions?expand=1

**Comment by mcanaves** [comment] 2017-07-21 08:01
Digging into the problem described by @xgilest and @aidanlister that the package do a query for each relation just to display the FK I found this piece of
[code](https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/renderers.py#L128-L132)

Maybe someone can clarify me the utility of this part because I can't see the purpose. As I understand this declaration only query to know if relation is resolved. Why we need to know if is resolved? Removing this part reduce the number of queries dramaticatly.

**Comment by jsenecal** [comment] 2017-07-21 12:35
I'll have to look it up as I didn't write that part :/

**Comment by jsenecal** [comment] 2017-07-21 17:20
FYI I started branch https://github.com/django-json-api/django-rest-framework-json-api/tree/issue-337 to work on this

**Comment by jsenecal** [comment] 2017-07-21 19:44
I am done for now, feel free to review #366 @aidanlister and @mblayman

**Comment by aidanlister** [comment] 2017-07-22 02:30
Looks great! Let's get it merged into develop and I'll rebase my WIP to look at the two parts of the query explosion.

**Comment by aidanlister** [comment] 2017-07-22 06:50
@jsenecal it would be amusing if we both caused and then later reported this explosion ... that commit you identified came from @jarekwg and @bor3ham (both from Uptick/ABAS). Here's the repository that PR came from:

https://github.com/jarekwg/django-rest-framework-json-api/commits/optimize/relationship-extraction

**Comment by jsenecal** [comment] 2017-07-22 07:07
I will now sign off but we need to open a separate issue as this is not yet completely resolved (we still have n*relation query explosion if queryset does not use `prefetch_related`)

**Comment by aidanlister** [comment] 2017-07-22 07:08
👍

**Comment by aidanlister** [comment] 2017-07-22 07:09
Keep this issue open? The PR is good but doesn't actually address this yet :)

**Comment by jsenecal** [comment] 2017-07-22 07:11
I guess you are right - Lets keep track of the discussion here

**Comment by aidanlister** [comment] 2017-07-22 10:47
Here's my progress on the explosion now:
https://github.com/django-json-api/django-rest-framework-json-api/compare/develop...ABASystems:wip/find-query-explosions

Note to anyone else playing along, you can run the project with ```django-admin.py shell --settings=example.settings.dev``` and run tests with ```py.test -s -k test_performance```

This code gets the first test to pass (test_query_count_no_includes) which is great ... but breaks on a simple include (test_query_count_include_author) which I haven't been able to debug yet (seems to start from extract_included)

**Comment by xgilest** [comment] 2017-07-24 08:20
Hi @mcanaves is working on a solution for the problem with the renderer quering to the database for checking the id of foreing keys exists. 
As stated earlier this meant for us that the API was to slow to be operational, hopefully with the great effort done by the community latelly, this will change.

**Comment by aidanlister** [comment] 2017-07-29 10:57
How's everyone going on this? Harder than it looks huh!

**Comment by jsenecal** [comment] 2017-07-29 13:34
I am actually waiting for Xavi to submit his work, no need to work in
parallel :/

**Comment by gregorypease280** [comment] 2017-10-14 00:02
anyone still actively working on this?

**Comment by aidanlister** [comment] 2017-10-18 04:19
No, not as far as I am aware. I wasn't able to progress it nor was @sksavant ... it's just whack-a-mole pushing the problem down the line.

DRF / JSON API has gotten so slow for us we're starting to think about something like Go, https://github.com/bor3ham/reja

**Comment by santiavenda2** [comment] 2017-12-07 03:44
Hi guys, 

Some time ago we did this [PR](https://github.com/django-json-api/django-rest-framework-json-api/pull/374/) trying to fix some of the problems that you mentioned during this conversation.

Let me know if the changes makes sense and if they are ready to be merged. 

All tests are running fine and we have been using this version in production without having any kind of problems.

**Comment by mblayman** [comment] 2017-12-12 16:16
Ack, my bad, @santiavenda2. I missed that the PR posted was related to this. I'll try to get it reviewed soon (hopefully this weekend if I have some free time). After all the discussion that happened here, I certainly did not intentionally overlook the PR. Thanks for the poke.

**Comment by aidanlister** [comment] 2017-12-13 12:14
@santiavenda2 neat, we will take a look too. Anything we should watch out for?

**Comment by santiavenda2** [comment] 2017-12-14 01:14
@aidanlister yes, these are the main changes
https://github.com/django-json-api/django-rest-framework-json-api/pull/374/files#diff-e2e58e3e5c345fc3b14c160b3a00a64cR127
https://github.com/django-json-api/django-rest-framework-json-api/pull/374/files#diff-e2e58e3e5c345fc3b14c160b3a00a64cR259
https://github.com/django-json-api/django-rest-framework-json-api/pull/374/files#diff-8f2fdb5cb1d819dce410d6b74d0b77b6R172

We tried to make two improvements:
 - try to not fetch related objects when we already have the id of the related object and we know the object type. 
 - also we avoid fetching related objects if the related object is None.

You can see these improvements in this [test](https://github.com/django-json-api/django-rest-framework-json-api/pull/374/files#diff-e009eaa5df551557d6bbf2300acb072bR76)
As you can see, the select_related and some of the prefetch_for_includes are not needed any more 

Other changes are just code quality improvements and fixes for code compatibility with old django versions.

**Comment by mblayman** [comment] 2018-01-09 02:04
With the work done in #374, do we have enough in place to call this issue fixed? Are there areas where DJA still issues too many queries?

**Comment by sliverc** [comment] 2018-06-08 11:53
Query explosion on simple models without inclusion looks now fine for me. I do still see issues when using included serializers though.

`views.AutoPrefetchMixin` does the lookup for direct included relationships. Such a relationship can have reverse relationships though and each of them still execute a query. I currently use `views.PrefetchForIncludesHelperMixin` as a workaround but `AutoPrefetchMixin` should prefetch reverse included relationships automatically though.

**Comment by timcbaoth** [comment] 2018-08-21 11:35
I stumbled upon this thread when I noticed a query explosion for a project at work. I found that there was a bug in https://github.com/django-json-api/django-rest-framework-json-api/pull/374/files#diff-e2e58e3e5c345fc3b14c160b3a00a64cR127 which resulted in the optimization of not querying forward relations not being applied.

I will provide a PR shortly, if that is OK.

**Comment by sliverc** [comment] 2021-04-18 17:47
Most of the concern in this PR actually have been addressed. There are still ways to reduce number of queries. Currently in this thread it is not clear what more needs to be done though.

So closing this issue and forward the conversation to discussion #921 and encourage everyone with an idea on reducing number of queries to engage there. Out of that discussion concrete new issues can then be extracted to work on.

**Closed by sliverc** 2021-04-18 17:47 UTC
Labels: bug, enhancement
