### ISSUE TITLE
Issue with relationships in POST/PATCH/PUT requests

### ISSUE THREAD

**Issue by martinmaillard** [django-json-api/django-rest-framework-json-api#122] opened 2015-10-09 13:20 UTC
If I do a POST request with data containing a relationship:

    {
        "data": {
            "type": "comments",
            "attributes": {
                "body": "Hi"
            },
            "relationships": {
                "entry": {
                    "data": {
                        "id": "12",
                        "type": "entries"
                    }
                }
            }
        }
    }

I get the following error:

    {
        "errors": [{
            "status": "400",
            "source": {"pointer": "/data/attributes/entry"}, 
            "detail": "Incorrect type. Expected pk value, received OrderedDict."
        }]
    }

I understand why this is happening, but I think this is a mistake.

**Comment by martinmaillard** [comment] 2015-10-09 13:34
This behaviour seems to have been introduced in https://github.com/django-json-api/django-rest-framework-json-api/commit/d654c757e9c034961261b642987c86a8affc2392

**Comment by jerel** [comment] 2015-10-09 13:40
It looks like this is probably a documentation bug on our part: you need to use `ResourceRelatedField` (from rest_framework_json_api.relations) for your relationship fields so it knows how to parse the incoming compound document

**Comment by jsenecal** [comment] 2015-10-09 13:43
@martinmaillard, @jerel is right - i introduced ResourceRelatedField to be able to parse things properly: https://github.com/django-json-api/django-rest-framework-json-api/commit/23d0af686ca9ad69ac8c63f45a7a08bf9656a459

See issue #111

**Comment by jsenecal** [comment] 2015-10-09 13:58
We could also override the `serializer_related_field` in both `HyperlinkedModelSerializer` and `ModelSerializer` so that we use the `ResourceRelatedField` by default, but in the case of `HyperlinkedModelSerializer` we would also need to override a few of the methods provided by DRF to supply the proper links.

**Comment by martinmaillard** [comment] 2015-10-09 13:59
Ok thank you, I didn't know that :)

Now it's working, but I still have an issue with the `type` validation... `ResourceRelatedField` is way too rigid when it checks the valid type. It gets the expected type from the queryset, which means that:

- it's not possible to customize the type of a relation (what is allowed by the `resource_name` on the serializer)
- it's not possible to allow multiple types to be valid for one relation (useful with polymorphic relationships)

**Comment by jsenecal** [comment] 2015-10-09 14:01
@martinmaillard I'm open to suggestions and PRs if you find a better way to validate the type as I am going to be busy for some time.

**Comment by jsenecal** [comment] 2015-10-09 14:08
I also think we should create a new issue for the behavior you are describing as it is out of the topic of this one.

This issue is a duplicate of #111, I will now close it.

**Closed by jsenecal** 2015-10-09 14:08 UTC

**Comment by martinmaillard** [comment] 2015-10-09 14:13
I will think about it, but it's a complicated issue. These `types` are all over the place and we need to centralize the way we generate/validate them.

Anyway thank you for your quick answers !

**Comment by jsenecal** [comment] 2015-10-09 14:23
No worries - also this issue made us realized we really need to document those features - I'll create a new one for that.

**Comment by riklaunim** [comment] 2015-12-21 15:39
How the ResourceRelatedField should be used? I still get that the related object is "places" instead of "Place"

**Comment by riklaunim** [comment] 2016-01-12 13:37
Any update on this? I would say expected type should not be the model name - https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/relations.py#L119 as everywhere else it's plural lowercase version of it.

**Comment by jerel** [comment] 2016-01-12 13:46
@riklaunim here is an example of the ResourceRelatedField in use: https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/example/serializers.py#L40-L41 If you could create a test that shows the unexpected behavior and open a PR we could discuss it better.

**Comment by riklaunim** [comment] 2016-01-12 14:37
ok, I missed two things ;)
```
JSON_API_FORMAT_RELATION_KEYS = 'dasherize'
JSON_API_PLURALIZE_RELATION_TYPE = True
```
