### ISSUE TITLE
ManyToMany queryset order is not preserved by ResourceRelatedSerializer

### ISSUE THREAD

**Issue by lucacorti** [django-json-api/django-rest-framework-json-api#475] opened 2018-09-12 08:23 UTC
Hi,

I'm serializing an included many to many relationship via `ResourceRelatedField` on the main resource serializer. I'm overriding the queryset to enforce a particular order and this is not reflected in the serializer output.

Why ResourceRelatedField does not honor queryset order? I guess this is a bug.

**Comment by sliverc** [comment] 2018-09-13 06:56
I don't see how `ResourceRelatedField` should not adhere to the many to many ordering. Also not sure whether this really concers DJA or rather DRF itself.

Question is though how you exactly enforce ordering of your ManyToMany field? Some example code would be helpful or at best a failing test in the DJA example app. Thanks.

**Comment by lucacorti** [comment] 2018-09-13 15:50
So, I have defined a many to many relationship between model A and model B with an explicit through model C.  I have defined an integer order field on C and I use it to sort items in my queryset. The queryset returns items in the correct order, but after serialization through ResourceRelatedField the order is not reflected in the 'relationships' output of the serializer.

**Comment by lucacorti** [comment] 2018-09-13 15:52
I'll try to come up with a failing test or sample code.

**Comment by lucacorti** [comment] 2018-09-13 15:54
Also, If I manually serialize the relationship through a SerializerMethodField the order is preserved, but then the related resource are not included in the output.

**Comment by sliverc** [comment] 2018-09-14 06:15
This sounds odd. It would be good to have a failing test or sample code - it will be easier to spot where the issue is.

**Comment by lucacorti** [comment] 2018-09-18 12:10
So, this is an example with some models and an explicit through relationship:

```
class Pizza(models.Model):
    # ...

class Topping(models.Model):
    # ...
    pizzas = models.ManyToManyField(Pizza, through='PizzaToppings', related_name='toppings')

class PizzaToppings(models.Model):
    pizza = models.ForeignKey(Pizza, related_name='pizzatoppings') 
    topping = models.ForeignKey(Topping, related_name='pizzatoppings')
    order = models.PositiveIntegerField(default=0)
```

Now, if you make a queryset like

```Pizza.objects.all.order_by('pizzatoppings__order')```

it will return the results in the correctly ordered.

But on a serializer for Pizza, settings the relationship field yields the wrong result (e.g. order by id):

```
class ToppingSerializer(serializers.ModelSerializer):
  # ...

  pizzas = ResourceRelatedField(queryset=Pizza.objects.alll().order_by('pizzatoppings__order'), many=True)
```

**Comment by sliverc** [comment] 2018-09-24 07:45
OK this makes sense that this doesn't work, as queryset of a relation fields is only used for limiting what can be written to a field and used as a lookup [see doc](http://www.django-rest-framework.org/api-guide/relations/#the-queryset-argument).

As you have a through model the field will need to be read only as of [DRF documentation](http://www.django-rest-framework.org/api-guide/relations/#manytomanyfields-with-a-through-model).

This means instead of a `ResourceRelatedField` you could use [SerializerMethodResourceRelatedField](https://django-rest-framework-json-api.readthedocs.io/en/stable/apidoc/rest_framework_json_api.relations.html#rest_framework_json_api.relations.SerializerMethodResourceRelatedField) like the following:

```python
class ToppingSerializer(serializers.ModelSerializer):
  # ...
  pizzas = SerializerMethodField(many=True)

  def get_pizzas(self, obj):
    return obj.pizzas.order_by('pizzatoppings__order')
```

Does this work for you?

**Comment by lucacorti** [comment] 2018-09-24 10:05
I tried it, and it works for preserving order, but unfortunately with this method you loose relationship information in the JSONAPI response.

**Comment by lucacorti** [comment] 2018-09-24 10:08
Ah sorry, I used `SerializerMethodField`, not `SerializerMethodResourceRelatedField`. I will try it.

**Comment by sliverc** [comment] 2018-09-25 11:39
Oh, my code sample was not correct... adjusted. Does it work for you this way now?

**Comment by sliverc** [comment] 2018-11-15 07:52
I assume above comment has helped. Closing this ticket therefore. If there are still questions please feel free to comment.

**Closed by sliverc** 2018-11-15 07:52 UTC
Labels: needs-information, question
